// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2XTRY7WDauNd6NwboIlKXd5-uwF635vo',
    appId: '1:569459730762:web:189e0dc4ba8622b56e39b3',
    messagingSenderId: '569459730762',
    projectId: 'vitalifebackend',
    authDomain: 'vitalifebackend.firebaseapp.com',
    storageBucket: 'vitalifebackend.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAATTCJcfcjfRHGX5jNvEPKPs_2QHCbG9o',
    appId: '1:569459730762:android:418d6e8c73c89e7d6e39b3',
    messagingSenderId: '569459730762',
    projectId: 'vitalifebackend',
    storageBucket: 'vitalifebackend.firebasestorage.app',
    androidClientId:
        '569459730762-p2cf5dsh9in4k0f4rrtqgb6ad1r9ef6d.apps.googleusercontent.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgbtwUiP1KjF-v6BXMqEa1Q7FpE02ooAk',
    appId: '1:569459730762:ios:1df68a86dc32838c6e39b3',
    messagingSenderId: '569459730762',
    projectId: 'vitalifebackend',
    storageBucket: 'vitalifebackend.firebasestorage.app',
    androidClientId:
        '569459730762-ea8i68r3c49inr6mtok22j79c2btog9t.apps.googleusercontent.com',
    iosClientId:
        '569459730762-1om810lhfhjpqos8v2q620l3bdlq1jh3.apps.googleusercontent.com',
    iosBundleId: 'com.example.vitalifeAsistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgbtwUiP1KjF-v6BXMqEa1Q7FpE02ooAk',
    appId: '1:569459730762:ios:1df68a86dc32838c6e39b3',
    messagingSenderId: '569459730762',
    projectId: 'vitalifebackend',
    storageBucket: 'vitalifebackend.firebasestorage.app',
    androidClientId:
        '569459730762-ea8i68r3c49inr6mtok22j79c2btog9t.apps.googleusercontent.com',
    iosClientId:
        '569459730762-1om810lhfhjpqos8v2q620l3bdlq1jh3.apps.googleusercontent.com',
    iosBundleId: 'com.example.vitalifeAsistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2XTRY7WDauNd6NwboIlKXd5-uwF635vo',
    appId: '1:569459730762:web:d4c1aea7564ebb376e39b3',
    messagingSenderId: '569459730762',
    projectId: 'vitalifebackend',
    authDomain: 'vitalifebackend.firebaseapp.com',
    storageBucket: 'vitalifebackend.firebasestorage.app',
    measurementId: 'G-5QL5HFEYMY',
  );
}
