// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEBI8l_AlrMSxeL8OoYDyq3xqAT5oIFUU',
    appId: '1:1026604075454:web:a95f7b83c68e67444c51ef',
    messagingSenderId: '1026604075454',
    projectId: 'vitalife-4eb12',
    authDomain: 'vitalife-4eb12.firebaseapp.com',
    storageBucket: 'vitalife-4eb12.firebasestorage.app',
    measurementId: 'G-B70TTWTVME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2Ea5t9NeGi8Yx_SsSDYJca0k6eY8sQWs',
    appId: '1:1026604075454:android:c2a14915e41cdaa44c51ef',
    messagingSenderId: '1026604075454',
    projectId: 'vitalife-4eb12',
    storageBucket: 'vitalife-4eb12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqjCUJiCC7ZJ56W-O3JMF2JQijuaBrDtc',
    appId: '1:1026604075454:ios:bb1cbe3d629d52ed4c51ef',
    messagingSenderId: '1026604075454',
    projectId: 'vitalife-4eb12',
    storageBucket: 'vitalife-4eb12.firebasestorage.app',
    iosBundleId: 'com.example.vitalifeAsistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqjCUJiCC7ZJ56W-O3JMF2JQijuaBrDtc',
    appId: '1:1026604075454:ios:bb1cbe3d629d52ed4c51ef',
    messagingSenderId: '1026604075454',
    projectId: 'vitalife-4eb12',
    storageBucket: 'vitalife-4eb12.firebasestorage.app',
    iosBundleId: 'com.example.vitalifeAsistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEBI8l_AlrMSxeL8OoYDyq3xqAT5oIFUU',
    appId: '1:1026604075454:web:cf563a11f2a8d9b64c51ef',
    messagingSenderId: '1026604075454',
    projectId: 'vitalife-4eb12',
    authDomain: 'vitalife-4eb12.firebaseapp.com',
    storageBucket: 'vitalife-4eb12.firebasestorage.app',
    measurementId: 'G-43HFWWC8JZ',
  );
}
